language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo add-apt-repository ppa:chris-lea/redis-server -y
  - sudo apt-get update -y

install:
  - pip install .
  - pip install -r requirements.txt --use-mirrors

# Command to run tests
script: nosetests

notifications:
    email:
	- coagentpai@gmail.com

